# Generated by Django 3.1 on 2020-08-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodinfo',
            name='num',
        ),
        migrations.AddField(
            model_name='foodinfo',
            name='unit',
            field=models.CharField(default='hogehoge', max_length=200),
            preserve_default=False,
        ),
    ]
