# Generated by Django 3.1 on 2020-08-25 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodinfo',
            name='food_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
